[workspace]
members = [
    "lattirust-arithmetic",
    "lattice-estimator",
    "relations",
    "sumcheck",
    "labrador",
    "lova",
    "hax"
]
resolver = "2"

[workspace.metadata.docs.rs]
# To build locally, use 
# RUSTDOCFLAGS="--html-in-header docs-header.html" cargo doc --no-deps --document-private-items --open
rustdoc-args = ["--html-in-header", "docs-header.html"]